# Generated by Django 2.1.5 on 2019-05-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('preview_url', models.URLField()),
                ('img_url', models.URLField()),
                ('tracks_number', models.IntegerField()),
                ('release_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genres', models.TextField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tempo', models.FloatField()),
                ('valence', models.FloatField()),
                ('liveness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('energy', models.FloatField()),
                ('danceability', models.FloatField()),
                ('track_path', models.FilePathField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=30)),
                ('preview_url', models.URLField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Artist'),
        ),
    ]
