# Generated by Django 2.1.5 on 2019-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='artist',
            field=models.CharField(max_length=30),
        ),
    ]
