# Generated by Django 2.1.5 on 2019-05-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20190510_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('track_id', models.CharField(max_length=30)),
            ],
        ),
    ]
